In [1]:
my_list = [1,2,3] #shif + tab para ver info

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])