In [1]:
my_list = [1,2,3] #shif + tab para ver info

In [3]:
my_list

[1, 2, 3]

In [6]:
import numpy as np


In [19]:
arr = np.array(my_list)


NameError: name 'my_list' is not defined

In [20]:
arr

NameError: name 'arr' is not defined

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [21]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.1541765 , 0.61608577, 0.9249146 , 0.55102694, 0.42566747])

In [26]:
np.random.rand(4,4)

array([[0.35356209, 0.72626377, 0.81839918, 0.76000253],
       [0.37863161, 0.28935785, 0.88567787, 0.28542455],
       [0.9512318 , 0.00985923, 0.79421443, 0.15573492],
       [0.14449982, 0.17180493, 0.67513877, 0.55691793]])

In [29]:
 np.random.randint(1,100)

5

In [30]:
 np.random.randint(1,100,10)

array([63, 31, 34, 23, 56, 91, 14, 43, 91, 57])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
narrn = np.random.randint(0,50,10)

In [34]:
narrn

array([49, 41, 35, 19, 38, 30, 41, 10, 39, 34])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
narrn.max()

49

In [40]:
narrn.min()

10

In [41]:
narrn

array([49, 41, 35, 19, 38, 30, 41, 10, 39, 34])

In [43]:
narrn.argmax()

0

In [44]:
narrn.argmin()

7

In [47]:
arr.shape

(25,)

In [48]:
narrn.shape

(10,)

In [50]:
arr = arr.reshape(5,5)

In [52]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape # de muestra la forma de la  matrix 5x5


(5, 5)

In [54]:
arr.dtype

dtype('int64')

In [57]:
from numpy.random import randint

In [58]:
randint(2,10)

4

In [59]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [61]:
array_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
array_2d[0]

array([1, 2, 3])

In [64]:
array_2d[0][0]

1

In [68]:
array_2d[1,2]

6

In [69]:
array_2d > 5


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [70]:
array_2d_ = array_2d >5

In [71]:
array_2d_

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [72]:
array_2d[array_2d_]

array([6, 7, 8, 9])